Repository SExOMC13/SExO-MC13, pull requests merged in 2021-06, with the labels that each got.

#3 Adds dreamchecker.exe
  dreamchecker.exe
Labels: Infrastructure

#4 bepis and conk milk
  code/game/objects/items/reagent_containers/food/cans.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/drinks.dmi
Labels: Feature

#5 Ports Arousal & Dildos
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/__HELPERS/_cit_helpers.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/status_effects/debuffs.dm
  code/modules/admin/holder.dm
  code/modules/arousal/arousal.dm
  code/modules/arousal/organs/breasts.dm
  code/modules/arousal/organs/genital_datum.dm
  code/modules/arousal/organs/genital_organ.dm
  code/modules/arousal/organs/penis.dm
  code/modules/arousal/organs/testicles.dm
  code/modules/arousal/organs/vagina.dm
  code/modules/arousal/organs/womb.dm
  code/modules/arousal/toys/dildos.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reagents/other.dm
  modular_skyrat/sound/weapons/gagging.ogg
  tgmc.dme
Labels: Feature, Work In Progress

#7 Bigger emote input box (and no automute)
  code/modules/mob/say.dm
  code/modules/mob/typing_indicator.dm
  config/config.txt
Labels: Tweak

#8 CLF infiltrator
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/hunt.dm
  code/datums/jobs/job/survivor.dm
  code/modules/clothing/suits/armor.dm
Labels: Feature

#10 More admin ranks
  config/admin_ranks.txt
  config/admins.txt
Labels: Tweak

#11 Server description for the hub
  code/controllers/configuration/entries/general.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/game/world.dm
  config/config.txt
Labels: Configuration Change

#9 Kinkmate Update
  code/game/objects/items/radio/electropack.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/restraints.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/ties.dm
  code/modules/reagents/reagents/medical.dm
  icons/mob/citadel/neck.dmi
  icons/mob/hands.dmi
  icons/mob/head_0.dmi
  icons/mob/mob.dmi
  icons/mob/ties.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cit_neck.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items/items.dmi
  icons/obj/machines/vending.dmi
Labels: Feature, Fix

#12 Non-lethal chestbursters
  code/game/objects/items/defibrillator.dm
  code/modules/arousal/organs/genital_datum.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/organ_internal.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Feature

#13 End round vote + xeno spawns
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/datums/gamemodes/extended.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  config/config.txt
Labels: Configuration Change, Feature

#14 A couple of tweaks
  code/__HELPERS/_cit_helpers.dm
  code/datums/gamemodes/extended.dm
Labels: Tweak

#15 Ingame server rules
  code/controllers/configuration/configuration.dm
  config/config.txt
  config/rules.txt
  interface/interface.dm
  interface/skin.dmf
Labels: Tweak

#16 Xeno-human communication
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Feature, Xenomorph

#18 Reverts admin note playtime tracking
  code/modules/admin/panels/note_panel.dm
Labels: Administration, Fix

#17 More tweaks
  code/__DEFINES/logging.dm
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/general.dm
  code/game/atoms.dm
  code/game/verbs/ooc.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  config/admin_ranks.txt
  config/config.txt
Labels: Administration, Marines, Tweak, Xenomorph

#19 gitignore for config files
  .gitignore
  config/example/admin_ranks.txt
  config/example/admins.txt
  config/example/config.txt
  config/example/dbconfig.txt
  config/example/in_character_filter.txt
  config/example/maps.txt
  config/example/modes.txt
  config/example/motd.txt
  config/example/policy.json
  config/example/resources.txt
  config/example/rules.txt
  config/example/shipmaps.txt
  tools/ci/run_server.sh
Labels: Configuration Change

#20 A few QOL tweaks
  code/controllers/subsystem/vote.dm
  code/datums/emotes.dm
  code/game/verbs/ooc.dm
  code/modules/admin/holder.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/say.dm
Labels: Administration, Tweak

#25 Upstream Merge Fix
  code/__DEFINES/logging.dm
  code/__DEFINES/traits.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/modules/admin/holder.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/reagents/reagents/other.dm
Labels: Fix

#22 Erp menu
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/mob.dm
  code/modules/striperp.dm
  sound/misc/sex1.ogg
  sound/misc/sex2.ogg
  sound/misc/sex3.ogg
  sound/voice/blowjob1.ogg
  sound/voice/blowjob2.ogg
  sound/voice/blowjob3.ogg
  sound/voice/blowjob4.ogg
  sound/voice/fingering1.ogg
  sound/voice/fingering2.ogg
  sound/voice/fingering3.ogg
  sound/voice/fingering4.ogg
  sound/voice/sexymoan_female1.ogg
  sound/voice/sexymoan_female2.ogg
  sound/voice/sexymoan_female3.ogg
  sound/voice/sexymoan_female4.ogg
  sound/voice/sexymoan_female5.ogg
  sound/voice/sexymoan_female6.ogg
  sound/voice/sexymoan_female7.ogg
  sound/voice/sexymoan_male1.ogg
  sound/voice/sexymoan_male2.ogg
  sound/voice/sexymoan_male3.ogg
  sound/voice/sexymoan_male4.ogg
  sound/voice/sexymoan_male5.ogg
  sound/weapons/slap.ogg
  tgmc.dme
Labels: Feature, Work In Progress

#26 Character slot hairstyle fix
  .vscode/settings.json
  code/modules/mob/living/carbon/human/species.dm
  code/modules/striperp.dm
Labels: Fix

#23 Client Age Verification
  SQL/database_changelog.txt
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/new_player.dm
Labels: Administration, SQL Change
